# The workflow is used to publish new release on every "version" file change.
name: Release

on:
  push:
    branches: [main]
    paths: [version]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create release
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          set -u
          . version
          echo "Creating release for ${SQLCMD_VERSION}"
          gh release create ${SQLCMD_VERSION} --latest
